spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: member-test
          uri: http://localhost:8081
          predicates:
            - Path=/test/**
          filters:
            - name: AuthorizationHeaderFilter
              args:
                headerName: Authorization
                granted: Bearer

        - id: ledger-server
          uri: http://localhost:8083
          predicates:
            - Path=/ledger/**
          filters:
            - name: AuthorizationHeaderFilter
              args:
                headerName: Authorization
                granted: Bearer
server:
  port: 8080
